language: java
addons:
  # ssh需要
  ssh_known_hosts: 47.96.3.69
  # sshpass需要
  apt:
    packages:
    - sshpass
jdk:
- oraclejdk8
script: mvn clean package -Dmaven.test.skip=true
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - fhxysdcz@126.com
    on_success: never # default: change
    on_failure: always # default: always
after_success:
- export SSHPASS=$DEPLOY_PASS
# - sshpass -e scp  -o stricthostkeychecking=no -r ./target/*.jar $SERVER_USER@$SERVER_HOST:/tmp
- sh deploy-to-github.sh
#- sshpass -e ssh  -o stricthostkeychecking=no $SERVER_USER@$SERVER_HOST "sh ./deploy-to-vps.sh "
- ssh $SERVER_USER@$SERVER_HOST "sh ./deploy-to-vps.sh "
env:
  global:
  # sshpass 需要
  - secure: FZ/F2nh0W+SM20X0yglUJD+4APgs6j9cC3O8KjCDQe5aowVhEKmfIZGwjGhNJVcIaPWTLBCPwRiusv6SjTb746aSD9hlj2/irh+/GSzgoA39M23RCi2o3QyOnSYcSZxl3BZShs7XYi1QBV5xHW8PJy4wqKpHJoOREqb7EMbVyIS7POBDiqTAW3I1fYe/qnHtiR0H0hmBeyFzNF+uUSNvV+RJAUU7dZ9i4FkcrRhZyXpuFjKXNzsYzft94XVOr1B2GSPSxzDO3MXFvB38/Uh+L3gviHeqzEOdus5Ts+eteYv/iW5jVuXesPi12OKAfxeo07NUmGGfXdHuwnGawHlYjONRgKj4PDT1gj3l4hZnzsQhNIlFnSz9oF3rzw9ADXGHZGbuZvBiCzwl3wDoQr1qOcwpQUIPNvUUwfi/GLFGEhFLfZ4r3udnCohN5SG+aRKj34RTEv3AXP7trbxRSllEfOG79IsZL2XyuxQP70ZEA1GucJFQAnWXSXsnwunG923F+8/AKGSQWZ5sLU7JkWJ/Oze0wdP/L+N1Vey7Hh86hcYVdU7+W1HPhKmbaAnklfqtx0M3UZbntt2Or/Asnrv6LYlVXJDydtccjt+ez9/da/lxgzEDHpczPc6XvqZZ1dPpmMlOVFOGM0yUAy1ZcFDPLMajkl68lCv0mWBLhI0qi9g=
  - secure: SXi+7a8aa1f1H3lf86lZwKw+iPuq/EMhnFApRFKObDuQpM7GABFtlPhIFv4hiVq07G1v8CrCT7wT+vY1xupdVuuMyWRjmRsXZj54s8ozpQU0CgcrWbgMpsLtictpeGKahGNKheEuc1wo9hhweN7kZuYE9Awfnj1jQGQxsCUpPInl0AxIXwv10zIJd6vOmI0YGEK9jrjnp80c0sxZErB/HE7nBFDsswKAUwotiSiFWPCeeQCf8UkSkdqnan2RVNeQucRq5hnknYx3u3/Zvf2Y1Wu5W1eW0rvVaB7N6FaLfEjyUfLEkji4H55Gx5hzh8EUFhrRsFn+GKSv7S4oqja5DgfrrFIEj6IOOA8V7vW9iFkCSenedUNVOI3whiAZs3TpQKiPoHKxxcm0zCXM23eYMhwyuwFJlL0ONJn6jXCxGyz2jJCQSLPjzRHMMCFVlS1g7+yTnr0Xy/7oMOStYOZ5SLeCt4k0iSe3v/iSLRLE87f8xwLlQ3IzN7BEXJgBXHi/lRsEta2w598hyBkdsHMZSGfGJU0lHo9ggq3DeqcANa3xsFFth0JJAv10b1anCxrPF+pSvPRWNlmcMnmJTkjXSeVggdgKvONqxyS1sZXyhwMcU4vv0twCmVy8U4QjZrzcqkcP3SlKEB2qWQF/kC1YOaeuSAmguYKs/MpyKgvZMZU=
before_install:
- openssl aes-256-cbc -K $encrypted_90f80e24f43c_key -iv $encrypted_90f80e24f43c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
